# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import AStarAlgorithmGUI
import GeneticAlgorithmGUI
import Backtracking
from Backtracking import VariableOrderings
from Backtracking import EarlyCheck


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(640, 431)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.greetingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.greetingsLabel.setGeometry(QtCore.QRect(200, 40, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.greetingsLabel.setFont(font)
        self.greetingsLabel.setObjectName("greetingsLabel")
        self.createdByLabel = QtWidgets.QLabel(self.centralwidget)
        self.createdByLabel.setGeometry(QtCore.QRect(190, 70, 261, 16))
        self.createdByLabel.setObjectName("createdByLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 89, 641, 351))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.backtrackingBtn = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        self.backtrackingBtn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.backtrackingBtn.setObjectName("backtrackingBtn")
        self.verticalLayout_6.addWidget(self.backtrackingBtn)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.numQueensBT = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.numQueensBT.setObjectName("numQueensBT")
        self.verticalLayout_6.addWidget(self.numQueensBT)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setObjectName("groupBox")
        self.fcRadio = QtWidgets.QRadioButton(self.groupBox)
        self.fcRadio.setGeometry(QtCore.QRect(-10, 20, 189, 20))
        self.fcRadio.setObjectName("fcRadio")
        self.acRadio = QtWidgets.QRadioButton(self.groupBox)
        self.acRadio.setGeometry(QtCore.QRect(-10, 40, 189, 20))
        self.acRadio.setMaximumSize(QtCore.QSize(16777215, 20))
        self.acRadio.setObjectName("acRadio")
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mrvRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.mrvRadio.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.mrvRadio.setObjectName("mrvRadio")
        self.mcvRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.mcvRadio.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.mcvRadio.setObjectName("mcvRadio")
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.lcvCheckbox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.lcvCheckbox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcvCheckbox.setObjectName("lcvCheckbox")
        self.verticalLayout_6.addWidget(self.lcvCheckbox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.geneticsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.geneticsBtn.setObjectName("geneticsBtn")
        self.verticalLayout.addWidget(self.geneticsBtn)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.numQueensGATF = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.numQueensGATF.setObjectName("numQueensGATF")
        self.verticalLayout.addWidget(self.numQueensGATF)
        self.populationSizeTF = QtWidgets.QLineEdit(
            self.horizontalLayoutWidget)
        self.populationSizeTF.setObjectName("populationSizeTF")
        self.verticalLayout.addWidget(self.populationSizeTF)
        self.maxGenerationsTF = QtWidgets.QLineEdit(
            self.horizontalLayoutWidget)
        self.maxGenerationsTF.setObjectName("maxGenerationsTF")
        self.verticalLayout.addWidget(self.maxGenerationsTF)
        self.mutationRateTF = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mutationRateTF.setObjectName("mutationRateTF")
        self.verticalLayout.addWidget(self.mutationRateTF)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aStarBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.aStarBtn.setObjectName("aStarBtn")
        self.verticalLayout_2.addWidget(self.aStarBtn)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.numQueensASTF = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.numQueensASTF.setObjectName("numQueensASTF")
        self.verticalLayout_2.addWidget(self.numQueensASTF)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.greetingsLabel.setText(_translate(
            "mainWindow", "Welcome to N-Queens Solver!"))
        self.createdByLabel.setText(_translate(
            "mainWindow", "Created by: Abdulelah Hajjar | s201727090 (Please PASTE the number in the textfields it types two letters there is a problem)"))
        self.backtrackingBtn.setText(_translate("mainWindow", "Solve"))
        self.backtrackingBtn.clicked.connect(
            lambda: self.backtrackingBtnClicked(self.numQueensBT.text(), self.fcRadio.isChecked(), self.acRadio.isChecked(), self.mrvRadio.isChecked(), self.mcvRadio.isChecked(), self.lcvCheckbox.isChecked()))

        self.label_5.setText(_translate("mainWindow", "Backtracking (PHW02)"))
        self.numQueensBT.setPlaceholderText(
            _translate("mainWindow", "Number of Queens"))
        self.groupBox.setTitle(_translate("mainWindow", "Filtering"))
        self.fcRadio.setText(_translate("mainWindow", "Forward Checking (FC)"))
        self.acRadio.setText(_translate("mainWindow", "Arc Consistency"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Variable Ordering"))
        self.mrvRadio.setText(_translate("mainWindow", "MRV"))
        self.mcvRadio.setText(_translate("mainWindow", "MCV"))
        self.lcvCheckbox.setText(_translate("mainWindow", "LCV"))
        self.geneticsBtn.setText(_translate("mainWindow", "Solve"))
        self.geneticsBtn.clicked.connect(lambda: self.gaBtnClicked(self.numQueensGATF.text(
        ), self.populationSizeTF.text(), self.maxGenerationsTF.text(), self.mutationRateTF.text()))
        self.label.setText(_translate("mainWindow", "Genetics Algorithm"))
        self.numQueensGATF.setPlaceholderText(
            _translate("mainWindow", "Number of Queens"))
        self.populationSizeTF.setPlaceholderText(
            _translate("mainWindow", "Population Size"))
        self.maxGenerationsTF.setPlaceholderText(
            _translate("mainWindow", "Maximum Number of Generations"))
        self.mutationRateTF.setPlaceholderText(
            _translate("mainWindow", "Mutation Rate (0-1)"))
        self.aStarBtn.setText(_translate("mainWindow", "Solve"))
        self.aStarBtn.clicked.connect(
            lambda: self.aStarBtnClicked(self.numQueensASTF.text()))
        self.label_2.setText(_translate("mainWindow", "A* Algorithm"))
        self.numQueensASTF.setPlaceholderText(
            _translate("mainWindow", "Number of Queens"))

    def gaBtnClicked(self, numQueens, populationCount, maxGens, mutationRate):
        GeneticAlgorithmGUI.start(
            int(numQueens), int(populationCount), int(maxGens), float(mutationRate))

    def aStarBtnClicked(self, numQueens):
        AStarAlgorithmGUI.start(int(numQueens))

    def backtrackingBtnClicked(self, numQueens, fc, arc, mrv, mcv, lcv):
        variableOrdering = None
        if mrv or mcv:
            variableOrdering = VariableOrderings.mrv if mrv else VariableOrderings.mcv

        earlyCheck = None
        if fc or arc:
            earlyCheck = EarlyCheck.fc if fc else EarlyCheck.arc

        Backtracking.start(int(numQueens), variableOrdering, earlyCheck, lcv)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
